### ISSUE TITLE
Wrong md5 for module.json

### ISSUE THREAD

**Issue by Foks5000** [LLoyderino/show-rng#1]
![image](https://user-images.githubusercontent.com/2840949/57988769-4d005180-7ad5-11e9-981f-16956fed209c.png)

**Comment by Zezo12345** [comment]
It still seem to work with this error there.

**Comment by LLoyderino** [comment]
@Foks5000 Hopefully [https://github.com/LLoyderino/show-rng/commit/7799d7611a7c0ed8d26c6d5e324097a9a2fa43b5](this) will solve the issue
